dailyfresh/apps/cart/urls.py
from django.conf.urls import url

urlpatterns = [
]

dailyfresh/apps/order/urls.py
from django.conf.urls import url

urlpatterns = [
]

dailyfresh/apps/user/urls.py
from django.conf.urls import url
from django.contrib.auth.decorators import login_required
from user import views
# from user.views import RegisterView
from user.views import LoginView, UserInfoView, UserOrderView, AddressView, LogoutView

urlpatterns = [
    url(r'^register$', views.register, name='register'),  # 注册
    url(r'^register_handle$', views.register_handle, name='register_handle'),  # 注册处理
    # url(r'^register$', RegisterView.as_view(), name='register'),  # 类视图, 用于前后端未分离
    url(r'^active/(?P<token>.*)$', views.active, name='active'),  # 用户激活
    # url(r'^login$', views.login, name='login'),
    url(r'^login$', LoginView.as_view(), name='login'),  # 登录使用类视图形式
    url(r'^logout$', LogoutView.as_view(), name='logout'),  # 注销登录
    url(r'^$', UserInfoView.as_view(), name='user'), # 用户中心信息页
    url(r'^order$', UserOrderView.as_view(), name='order'), #
    url(r'^address$', AddressView.as_view(), name='address'),
]

dailyfresh/dailyfresh/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^tinymce/', include('tinymce.urls')), # 副文本编辑器
    url(r'^user/', include('user.urls', namespace='user')), # 用户模块
    url(r'^cart/', include('cart.urls', namespace='cart')), # 购物车模块
    url(r'^order/', include('order.urls', namespace='order')), # 订单模块
    url(r'^', include('goods.urls', namespace='goods')), # 商品模块
]

dailyfresh/apps/cart/models.py
from django.db import models

# Create your models here.

dailyfresh/apps/order/models.py
from django.db import models
from db.base_model import BaseModel

class OrderInfo(BaseModel):
    '''订单模型类'''
    PAY_METHOD_CHOICES = (
        (1, '货到付款'),
        (2, '微信支付'),
        (3, '支付宝'),
        (4, '银联支付'),
    )

    ORDER_STATUS_CHOICES = (
        (1, '待支付'),
        (2, '待发货'),
        (3, '待收货'),
        (4, '待评价'),
        (5, '已完成'),
    )

    order_id = models.CharField(max_length=128, primary_key=True, verbose_name='订单id')
    user = models.ForeignKey('user.User', verbose_name='用户')
    addr = models.ForeignKey('user.Address', verbose_name='地址')
    pay_method = models.SmallIntegerField(choices=PAY_METHOD_CHOICES, default=2)
    total_count = models.IntegerField(default=1, verbose_name='商品数量')
    total_price = models.DecimalField(max_digits=10, decimal_places=2, verbose_name='商品总价格')
    transit_price = models.DecimalField(max_digits=10, decimal_places=2, verbose_name='运费')
    order_status = models.SmallIntegerField(choices=ORDER_STATUS_CHOICES, default=1, verbose_name='支付状态')
    trade_no = models.CharField(max_length=128, verbose_name='支付编号')

    class Meta:
        db_table = 'df_order_info'
        verbose_name = '订单'
        verbose_name_plural = verbose_name


class OrderGoods(BaseModel):
    '''订单商品模型类'''
    order = models.ForeignKey('OrderInfo', verbose_name='订单')
    sku = models.ForeignKey('goods.GoodsSKU', verbose_name='商品SKU')
    count = models.IntegerField(default=1, verbose_name='商品数目')
    price = models.DecimalField(max_digits=10, decimal_places=2, verbose_name='商品价格')
    comment = models.CharField(max_length=256, verbose_name='评论')

    class Meta:
        db_table = 'df_order_goods'
        verbose_name = '订单商品'
        verbose_name_plural = verbose_name

dailyfresh/apps/user/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from db.base_model import BaseModel
# Create your models here.

class User(AbstractUser, BaseModel):
    '''用户模型类'''
    class Meta:
        db_table = 'df_user'
        verbose_name = '用户'
        verbose_name_plural = verbose_name

class AddressManager(models.Manager):
    '''地址模型管理器类'''
    # 1. 改变原有的结果集：all()
    # 2. 封装方法：用户操作模型类对应的数据表（增删改查）
    def get_default_address(self, user):
        '''获取用户的默认收货地址'''
        # self.model:获取self对象所在的模型类
        try:
            # address = Address.objects.get(user=user, is_default=True) # 避免下面的Address这个类名字变化之后引发报错，使用self.model来获取
            # address = self.model.objects.get(user=user, is_default=True) # self就是AddressManager这个类的，可以调用Manager这个类的get方法
            address = self.get(user=user, is_default=True)
        except self.model.DoesNotExist:
            # 不存在默认收货地址
            address = None
        return address

class Address(BaseModel):
    '''地址模型类'''
    user = models.ForeignKey('User', verbose_name='所属账户')
    receiver = models.CharField(max_length=20, verbose_name='收件人')
    addr = models.CharField(max_length=256, verbose_name='收件地址')
    zip_code = models.CharField(max_length=6, null=True, verbose_name='邮政编码')
    phone = models.CharField(max_length=11, verbose_name='联系电话')
    is_default = models.BooleanField(default=False, verbose_name='是否默认')

    objects = AddressManager()
    class Meta:
        db_table = 'df_address'
        verbose_name = '地址'
        verbose_name_plural = verbose_name

dailyfresh/apps/cart/views.py
from django.shortcuts import render

# Create your views here.

dailyfresh/apps/order/views.py
from django.shortcuts import render

# Create your views here.

dailyfresh/apps/user/views.py
from django.shortcuts import render, redirect
from django.core.urlresolvers import reverse # 处理前后端未分离的跳转
from django.views.decorators.csrf import csrf_exempt  # 处理csrf报错 @csrf_exempt
from django.http import HttpResponse, JsonResponse  # 处理返回数据
from django.core.mail import send_mail
from django.conf import settings  # 使用其中 SECRET_KEY 作为密钥  使用其中的send_mail配置
from django.contrib.auth import authenticate, login, logout
from utils.mixin import LoginRequiredMixin

from itsdangerous import TimedJSONWebSignatureSerializer as Serializer
from itsdangerous import SignatureExpired
from user.models import User, Address
from goods.models import GoodsSKU
import re
import json
from celery_tasks.tasks import send_register_active_email
from django.views.generic import View
from django_redis import get_redis_connection

# Create your views here.

# /user/register
def register(request):
    '''显示注册页面'''
    return render(request, 'register.html')


# 解除django框架csrf限制
@csrf_exempt
def register_handle(request):
    '''进行注册处理'''
    # 接受数据(下面是通过表单接受的)
    # username = request.POST.get('username')
    # passwd = request.POST.get('passwd')
    # mail = request.POST.get('mail')
    # single = request.POST.get('single')
    # 通过axios提交通过request.body提交的经过转换得到的数据
    # data_byte = request.body
    # data_str = data_byte.decode()
    # data_json = json.loads(data_str)
    data = json.loads(request.body.decode())
    print(request.method)
    username = data.get('username')
    passwd = data.get('passwd')
    mail = data.get('mail')
    single = data.get('single')

    # 进行数据校验
    if not all([username, passwd, mail]):
        # 数据不完整
        # return render(request, 'register.html', {'errmsg':'数据不完整'})
        result = {"status": "error", "msg": "请将数据填写完整"}
        return JsonResponse(result)
    # 校验邮箱
    if not re.match(r'[a-zA-Z0-9][\w\.\-]*@[a-zA-Z0-9\-]+(\.[a-z]{2,5}){1,2}$', mail):
        # return render(request, 'register.html', {'msg': '邮箱不合法'})
        mailresult = {"status": "error", "msg": "邮箱不合法"}
        return JsonResponse(mailresult)
    # 判断勾选
    if single != True:
        singleresult = {"status": "error", "msg": "请勾选协议"}
        return JsonResponse(singleresult)
        # return render(request, 'register.html', {'msg': '请勾选协议'})
    # 校验用户名是否重复
    try:
        is_dou_user = User.objects.get(username=username)
    except User.DoesNotExist:
        # 用户名不存在
        is_dou_user = None

    if is_dou_user:
        is_dou_userresult = {"status": "error", "msg": "用户名已经存在，请重新输入一个用户名"}
        return JsonResponse(is_dou_userresult)

    # 进行业务处理：进行用户注册
    # user = User()
    # user.username = username
    # user.passwd = passwd
    # user.mail = mail
    # user.single = single
    # user.save()
    user = User.objects.create_user(username, mail, passwd)
    user.is_active = 0  # 设置账户未激活，默认是已激活
    user.save()

    # 发送激活邮件，包含激活链接,并且要把身份信息加密
    # 加密用户身份信息,生成激活的token
    serializer = Serializer(settings.SECRET_KEY, 3600)
    info = {'confirm': user.id}
    token = serializer.dumps(info)  # bytes
    token = token.decode('utf8')  # 解码

    # 发送邮件
    subject = '天天生鲜欢迎信息'
    message = ''
    sender = settings.EMAIL_FROM  # 发件人
    receiver = [mail]  # 收件人
    html_message = '<h1>%s, 欢迎您成为天天生鲜注册会员</h1>请点击下面链接激活您的帐户<br/><a href="http://192.168.1.108:8000/user/active/%s">http://192.168.1.108:8000/user/active/%s</a>' % (
    username, token, token)
    send_mail(subject, message, sender, receiver, html_message=html_message)  # 发送带有html标签的内容时候需要使用html_message这个字段
    # 异步celery有点问题,启动需要在目标机器启动使用
    # send_register_active_email.delay(mail, username, token) # delay()是经过@app.task函数装饰以后才有的函数

    # 返回应答
    response = {"status": "success", "msg": "注册成功"}
    return JsonResponse(response)
    # return redirect(reverse('goods:index')) # 前后端未分离写法


# class RegisterView(View): # 适合前后端未分离，建议不要用
#     '''注册'''
#     def get(self, request):
#         '''显示注册页面'''
#         return render(request, 'register.html')
#     def post(self, request):
#         '''进行注册处理'''
#         data = json.loads(request.body.decode())
#         print(request.method)
#         username = data.get('username')
#         passwd = data.get('passwd')
#         mail = data.get('mail')
#         single = data.get('single')
#
#         # 进行数据校验
#         if not all([username, passwd, mail]):
#             # 数据不完整
#             # return render(request, 'register.html', {'errmsg':'数据不完整'})
#             result = {"status": "error", "msg": "请将数据填写完整"}
#             return JsonResponse(result)
#         # 校验邮箱
#         if not re.match(r'[a-zA-Z0-9][\w\.\-]*@[a-zA-Z0-9\-]+(\.[a-z]{2,5}){1,2}$', mail):
#             # return render(request, 'register.html', {'msg': '邮箱不合法'})
#             mailresult = {"status": "error", "msg": "邮箱不合法"}
#             return JsonResponse(mailresult)
#         # 判断勾选
#         if single != True:
#             singleresult = {"status": "error", "msg": "请勾选协议"}
#             return JsonResponse(singleresult)
#             # return render(request, 'register.html', {'msg': '请勾选协议'})
#         # 校验用户名是否重复
#         try:
#             is_dou_user = User.objects.get(username=username)
#         except User.DoesNotExist:
#             # 用户名不存在
#             is_dou_user = None
#
#         if is_dou_user:
#             is_dou_userresult = {"status": "error", "msg": "用户名已经存在，请重新输入一个用户名"}
#             return JsonResponse(is_dou_userresult)
#
#         # 进行业务处理：进行用户注册
#         # user = User()
#         # user.username = username
#         # user.passwd = passwd
#         # user.mail = mail
#         # user.single = single
#         # user.save()
#         user = User.objects.create_user(username, mail, passwd)
#         user.is_active = 0  # 设置账户未激活，默认是已激活
#         user.save()
#
#         # 返回应答
#         response = {"status": "success", "msg": "注册成功"}
#         return JsonResponse(response)
#         # return redirect(reverse('goods:index')) # 前后端未分离写法

def active(request, token):
    '''用户激活链接'''
    # 进行解密， 获取需要激活的信息
    serializer = Serializer(settings.SECRET_KEY, 3600)

    try:
        info = serializer.loads(token)
        # 获取待激活用户id
        user_id = info['confirm']
        # 根据id获取用户信息
        user = User.objects.get(id=user_id)
        user.is_active = 1
        user.save()

        # 激活之后的跳转(应该直接提示激活成功)
        # activeresult = {"status": "success", "msg": "激活成功"}
        # return JsonResponse(activeresult)
        return HttpResponse('邮箱激活成功')

    except SignatureExpired as e:
        # 激活链接已过期
        expireToken = {"status": "error", "msg": "激活链接已过期"}
        return JsonResponse(expireToken)


# def login(request):
#     '''显示登录页面'''
#     return render(request, 'login.html')


# 前后端未分离写法
class LoginView(View):
    '''登录的类视图'''

    def get(self, request):
        '''显示登录页面'''
        return render(request, 'login.html')

    @csrf_exempt
    def post(self, request):
        '''登录校验'''
        # 接受数据
        data = json.loads(request.body.decode())
        username = data.get('username')
        password = data.get('passwd')
        rempasswd = data.get('rempasswd')
        # 校验数据
        if not all([username, password]):
            return render(request, 'login.html', {'errmsg': '数据不完整'})
        # 业务处理，登录校验
        user = authenticate(username=username, password=password)
        if user is not None:
            # 用户名密码正确
            if user.is_active:
                # 用户已激活
                # 记录用户的状态
                login(request, user)

                response = redirect(reverse('goods:index'))
                # 判断是否需要记住用户名
                print(rempasswd)
                print(rempasswd == True)
                if rempasswd == True:
                    # 记住用户名
                    response.set_cookie('username', username, max_age=7*24*3600)
                else:
                    response.delete_cookie('username')

                # return redirect('user:user')
                return JsonResponse({"status": "success", "msg": "登陆成功"}
)
            else:
                return render(request, 'login.html', {'errmsg': '账户未激活'})
        else:
            # 用户名密码错误
            return render(request, 'login.html', {'errmsg':'用户名密码错误'})


        # 返回应答

# 前后端分写法
# class LoginView(View):
#     '''登录的类视图'''
#
#     def get(self, request):
#         '''显示登录页面'''
#         if 'username' in request.COOKIES: #根据cooki自动填充
#             username = request.COOKIES.get('username')
#             print(username)
#         else:
#             username = ''
#             return render(request, 'login.html')
#
#     @csrf_exempt
#     def post(self, request):
#         '''登录校验'''
#         # 接受数据
#         data = json.loads(request.body.decode())
#         username = data.get('username')
#         passwd = data.get('passwd')
#         rempasswd = data.get('rempasswd')
#         # 校验数据
#         if not all([username, passwd]):
#             result = {"status": "error", "msg": "请将用户名和密码填写完整"}
#             return JsonResponse(result)
#
#         # 业务处理
#         user = authenticate(username=username, password=passwd) # redis记住登录状态
#         if user is not None:
#             # 用户名密码正确
#             if user.is_active:
#                 # 用户已激活
#                 # 使用redis记住用户登录状态
#                 print(user)
#                 # login(request, user) # redis连接还有点问题
#                 # next_url = request.GET.get('next', reverse('goods:index'))
#                 # response = redirect(next_url)
#
#                 # 判断是否需要记住用户名
#                 response = HttpResponse() # 使用response设置cookie
#                 if rempasswd == True: # 前端做存储
#                     # 记住用户名
#                     response.set_cookie('username', username, max_age=7 * 24 * 3600)
#                 else:
#                     response.delete_cookie('username')
#
#                 success_active = {"status": "success", "msg": "登陆成功"}
#                 return JsonResponse(success_active)
#
#             else:
#                 # 用户未激活

dailyfresh/templates/address.html
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<title>收货地址</title>
	<link rel="stylesheet" href="/static/css/iview.css">
	<link rel="stylesheet" type="text/css" href="/static/css/common.css">
	<script src="/static/js/vue.js"></script>
	<script src="/static/js/iview.js"></script>
	<script src="/static/js/axios.js"></script>
</head>
<body>
		<div id="app">
		<Row :gutter=20>
			<i-col :span='24'>
				<div class='disflex jcsb plf20 user-title'>
					<div>欢迎来到天天生鲜</div>
					<div>
						{% if user.is_authenticated %}
						<span class='ml20 curpon'>欢迎您： <span>{{user.username}}</span></span>
						<span><a href="{% url 'user:logout' %}">退出登录</a></span>
						{% else %}
						<span class='ml20 curpon'><a href="{% url 'user:login' %}" title="登录">登录</a></span>
						<span class='ml20 curpon'><a href="{% url 'user:register' %}" title="注册">注册</a></span>
						{% endif %}
						<span class='ml20 curpon'><a href="{% url 'user:user' %}" title="用户中心">用户中心</a></span>
						<span class='ml20 curpon'><a href="/user/cart" title="购物车">购物车</a></span>
						<span class='ml20 curpon'><a href="{% url 'user:order' %}" title="我的订单">我的订单</a></span>
					</div>
				</div>
			</i-col>
			<i-col :span=24>
				<div style='margin: 0 auto; width: 50%' class='mt20 mb20'>
					<i-input v-model.trim="search" search enter-button="搜索" placeholder="请输入搜索商品" />
				</div>
			</i-col>
			<i-col :span=24>
				<Row :gutter=20>
					<i-col :span='5' :offset='1'>
						<div class='user-center'>
							<div class='pt20'>用户中心</div>
							<div>
								<ul>
									<li class='mt20'><a href="{% url 'user:user' %}">个人信息</a></li>
									<li class='mt20'><a href="{% url 'user:order' %}">全部订单</a></li>
									<li class='mt20'><a class='active' href="{% url 'user:address' %}">收货地址</a></li>
								</ul>
							</div>
						</div>
					</i-col>
					<i-col :span='15'>
						<div>
							<div>
								<div>
									<h2>收货地址</h2>
								</div>
								<div class='user-menage'>
									<div>当前地址：</div>
									{% if address %}
									<div>{{address.addr}} （{{address.receiver}} 收） {{address.phone}}</div>
									{% else %}
									<div>请添加地址</div>
									{% endif %}
								</div>
							</div>
							<div>
								<div>
									<h2>编辑地址</h2>
								</div>
								<div class='user-menage'>
									<div class='disflex mt20'>
										<div>收件人t</div>
										<div><i-input v-model.trim='name' placehplder='收件人名字'/>	</div>
									</div>
									<div class='disflex mt20'>
										<div>详细地址</div>
										<div><i-input v-model.trim='address' type="textarea" placehplder='详细地址'/>	</div>
									</div>
									<div class='disflex mt20'>
										<div>邮编</div>
										<div><i-input v-model.trim='zipCode' placehplder='邮政编码'/>	</div>
									</div>
									<div class='disflex mt20'>
										<div>手机</div>
										<div><i-input v-model.trim='phone' placehplder='手机号码'/>	</div>
									</div>
									<div class='mt20'>
										<i-button @click='submit'>提交</i-button>
									</div>
								</div>
							</div>
						</div>
					</i-col>
				</Row>
			</i-col>
		</Row>
	</div>
</body>
</html>

<script>
	new Vue({
		el: '#app',
		data:{
			search: '',
			name: '',
			address: '',
			zipCode: '',
			phone: ''
		},
		methods: {
			submit () {
				axios.post('/user/address', {
					name: this.name,
					addr: this.address,
					zipCode: this.zipCode,
					phone: this.phone
				}).then((res) => {
					console.log(res)
				})
			},
		},
		mounted () {}
	})
</script>

dailyfresh/templates/login.html
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<title>登录</title>
	<link rel="stylesheet" href="/static/css/iview.css">
	<link rel="stylesheet" type="text/css" href="/static/css/common.css">
	<style type="text/css" media="screen">
		#app {
			padding-top: 50px;
			text-align: center;
		}
	</style>
</head>
<body>
	<div id="app">
		<Row>
			<i-col :span='24'>
				用户名：
				<i-input v-model.trim="username" placeholder="用户名" style="width: 300px" />
			</i-col>
			<i-col :span='24'>
				密码：
				<i-input v-model.trim="passwd" placeholder="密码" style="width: 300px" />
			</i-col>
			<i-col :span='24'>
				<Checkbox v-model.trim="rempasswd">记住密码</Checkbox>
			</i-col>
			<i-col :span='24'>

			</i-col>
			<i-col :span='24'>
				<i-button type="success" long style="width: 300px" @click='login'>登录</i-button>
			</i-col>
			{{errmsg}}

		</Row>
	</div>
</body>
</html>
<script src="/static/js/vue.js"></script>
<script src="/static/js/iview.js"></script>
<script src="/static/js/axios.js"></script>
<script>
	new Vue({
		el: '#app',
		data:{
			username: '',
			passwd: '',
			rempasswd: false
		},
		mounted () {},
		methods: {
			login () {
				axios.post('/user/login', {
				    username: this.username,
				    passwd: this.passwd,
				    rempasswd: this.rempasswd
                }).then((res) => {
					// console.log(res)
                    if (res.data.status === 'success') {
                        window.location.replace('/')
                    } else {
                        this.$Message.info(res.data.msg)
                    }
				})
			}
		}
	})
</script>

dailyfresh/templates/order.html
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<title>订单页面</title>
	<link rel="stylesheet" href="/static/css/iview.css">
	<link rel="stylesheet" type="text/css" href="/static/css/common.css">
	<script src="/static/js/vue.js"></script>
	<script src="/static/js/iview.js"></script>
	<script src="/static/js/axios.js"></script>
</head>
<body>
		<div id="app">
		<Row>
			<i-col :span='24'>
				<div class='disflex jcsb plf20 user-title'>
					<div>欢迎来到天天生鲜</div>
					<div>
						{% if user.is_authenticated %}
						<span class='ml20 curpon'>欢迎您： <span>{{user.username}}</span></span>
						<span><a href="{% url 'user:logout' %}">退出登录</a></span>
						{% else %}
						<span class='ml20 curpon'><a href="{% url 'user:login' %}" title="登录">登录</a></span>
						<span class='ml20 curpon'><a href="{% url 'user:register' %}" title="注册">注册</a></span>
						{% endif %}
						<span class='ml20 curpon'><a href="{% url 'user:user' %}" title="用户中心">用户中心</a></span>
						<span class='ml20 curpon'><a href="/user/cart" title="购物车">购物车</a></span>
						<span class='ml20 curpon'><a href="{% url 'user:order' %}" title="我的订单">我的订单</a></span>
					</div>
				</div>
			</i-col>
			<i-col span='24'>
				<div style='margin: 0 auto; width: 50%' class='mt20 mb20'>
					<i-input v-model.trim="search" search enter-button="搜索" placeholder="请输入搜索商品" />
				</div>
			</i-col>
			<i-col span='24'>
				<Row>
					<i-col span='5' offset='1'>
						<div class='user-center'>
							<div class='pt20'>用户中心</div>
							<div>
								<ul>
									<li class='mt20'><a href="{% url 'user:user' %}">个人信息</a></li>
									<li class='mt20'><a class='active' href="{% url 'user:order' %}">全部订单</a></li>
									<li class='mt20'><a href="{% url 'user:address' %}">收货地址</a></li>
								</ul>
							</div>
						</div>
					</i-col>
					<i-col span='18'>
						<!-- 订单模块start -->
						<div class='mt20'>
						    <Card style="width:100%" class='mt20' v-for='(item) in goodsList' :key='item.id'>
						        <p slot="title">
						            <span class='ml20'>{{item.time}}</span>
						            <span class='ml20'>订单编号：{{item.ordernumber}}</span>
						            <span class='ml20 active'>{{item.payResult}}</span>
						        </p>
						        <ul>
						           <li>
						           		<div class='disflex'>
						           			<div>
							           			<ul>
							           				<li class="disflex" v-for='(sonitem) in item.list' :key='sonitem.id'>
							           					<div class='ml20'><img class='img' :src="sonitem.img" alt=""></div>
							           					<div class='ml40 lh50'>{{sonitem.title}}</div> 
							           					<div class='ml40 lh50'><span>{{sonitem.price}}</span>/<span>{{sonitem.quality}}</span></div>
							           					<div class='ml40 lh50'>{{sonitem.number}}</div>
							           					<div class='ml40 lh50'>{{sonitem.utilPrice}}</div>
							           				</li>
							           			</ul>
							           		</div>
							           		<div class='line ml20 disflex'>
							           			<div class='price-one ml20 lh100 price' style='margin-left: 100px;'>{{item.totalPrice}}元</div>
							           			<div class='price-two ml20 lh100 price' style='margin-left: 100px;'>{{item.payStatus}}</div>
							           			<div class='price-three ml20 lh100 price' style='margin-left: 100px;'><i-button type='success'>去付款</i-button></div>
							           		</div>
						           		</div>
						           </li>
						        </ul>
						    </Card>



						</div>
						<!-- 订单模块end -->
					</i-col>
				</Row>
			</i-col>
		</Row>
	</div>
</body>
</html>

<script>
	new Vue({
		el: '#app',
		data:{
			goodsList: [
				{
					id: 1,
					time: '2019年11月5日09:40:23',
					ordernumber: '56546516',
					payResult: '已支付',
					list: [
						{
							id: 11,
							title: '苹果',
							price: '11.80',
							quality: '500g',
							number: '1',
							img: '/static/img/2.jpeg',
							utilPrice: '11.80',
						},{
							id: 12,
							title: '苹果',
							price: '11.80',
							quality: '500g',
							number: '1',
							img: '/static/img/1.jpeg',
							utilPrice: '11.80',
						}
					],
					totalPrice: '25.60',
					payStatus: '待付款',
				},{
					id: 2,
					time: '2019年11月5日09:40:23',
					ordernumber: '56546516',
					payResult: '已支付',
					list: [
						{
							id: 21,
							title: '香蕉',
							price: '11.80',
							quality: '500g',
							number: '1',
							img: '/static/img/1.jpeg',
							utilPrice: '11.80',
						},{
							id: 22,
							title: '香蕉',
							price: '11.80',
							quality: '500g',
							number: '1',
							img: '/static/img/2.jpeg',
							utilPrice: '11.80',
						}
					],
					totalPrice: '25.60',
					payStatus: '待付款',
				},{
					id: 2,
					time: '2019年11月5日09:40:23',
					ordernumber: '56546516',
					payResult: '已支付',
					list: [
						{
							id: 21,
							title: '香蕉',
							price: '11.80',
							quality: '500g',
							number: '1',
							img: '/static/img/1.jpeg',
							utilPrice: '11.80',
						},{
							id: 22,
							title: '香蕉',
							price: '11.80',
							quality: '500g',
							number: '1',
							img: '/static/img/2.jpeg',
							utilPrice: '11.80',
						}
					],
					totalPrice: '25.60',
					payStatus: '待付款',
				}
			],
			search: ''
		},
		methods: {},
		mounted () {}
	})
</script>

dailyfresh/templates/user_center_address.html
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<title></title>
	<link rel="stylesheet" href="/static/css/iview.css">
</head>
<body>
	<div id="app">
		<Row>
			<i-col :span='24'>
                <h1>地址页面</h1>
			</i-col>
		</Row>
	</div>
</body>
</html>
<script src="/static/js/vue.js"></script>
<script src="/static/js/iview.js"></script>
<script src="/static/js/axios.js"></script>
<script>
	new Vue({
		el: '#app',
		data:{},
		methods: {},
		mounted () {}
	})
</script>